<?php

$_COS_LANG_MODULE['Login'] = 'Logon';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> for at stemme';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'For at stemme skal du logge ind Tryk stemme knappen og du vil gå til login siden. Efter log ind, vil du vende tilbage her.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'Du har allerede stemt';
