<?php

$_COS_LANG_MODULE['Please login in order to make a vote'] = '请登录以进行投票';
$_COS_LANG_MODULE['Login'] = '注册';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span>投票';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = '为了投票，您需要登录。按下投票按钮，您将进入登录页面。之后日志中你会回到这里。';
$_COS_LANG_MODULE['vote_user_has_voted'] = '您已投票';
