<?php


// Translation of file /modules/vote/module.php

$_COS_LANG_MODULE['Login'] = 'Login';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> to vote ';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'You have already voted';
