<?php

$_COS_LANG_MODULE['Please login in order to make a vote'] = 'Du må være innlogget for å kunne gjøre en stemme';
$_COS_LANG_MODULE['Login'] = 'Innlogging';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> for å stemme';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'For å stemme må du logge inn Trykk stemme knappen, og du vil gå til innloggingssiden. Etter innlogging vil du komme tilbake hit.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'Du har allerede stemt';
