<?php

$_COS_LANG_MODULE['Login'] = 'Anmelden';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> abstimmen';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'Um abzustimmen, müssen eingeloggt Abstimmung Taste drücken, und Sie werden in die Log-in-Seite zu gehen. Nach dem Login finden Sie hier zurückkehren.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'Sie haben bereits abgestimmt';
