<?php

$_COS_LANG_MODULE['Login'] = 'Käyttäjätunnus';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> äänestää';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'Äänestämistä varten sinun täytyy kirjautua sisään painamalla äänestys-painiketta ja siirryt kirjautumissivulle. Jälkeen Kirjaudu palaat tänne.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'Olet jo äänestänyt';
