<?php

$_COS_LANG_MODULE['Login'] = 'Inloggning';
$_COS_LANG_MODULE['<span class="notranslate">{LOGIN_LINK}</span> to vote '] = '<span class="notranslate">{LOGIN_LINK}</span> för att rösta';
$_COS_LANG_MODULE['In order to vote you need to log in. Press vote button and you will go to the log in page. After log in you will return here.'] = 'För att rösta måste du logga in Tryck rösta-knappen och du kommer att gå till inloggningssidan. Efter inloggning kommer du att återvända hit.';
$_COS_LANG_MODULE['vote_user_has_voted'] = 'Du har redan röstat';
